apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio
  template:
    metadata:
      labels:
        app: audio
    spec:
      containers:
        - name: audiobookshelf
          image: advplyr/audiobookshelf:2.35.0
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "America/Toronto"

          volumeMounts:
            - name: audio-storage
              mountPath: /config
              subPath: config
            - name: audio-storage
              mountPath: /metadata
              subPath: metadata
            - name: audio-storage
              mountPath: /audiobooks
              subPath: audiobooks
            - name: audio-storage
              mountPath: /podcasts
              subPath: podcasts

      volumes:
        - name: audio-storage
          persistentVolumeClaim:
            claimName: audio-data-pvc
