apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:FCg6VFKCoSaAI8BHJ02b/43ckYppmFw/B8H0FztvbIieh6ySjtF2zBbevMt5c5rk1pZkFygVp5On0SJ0itfQoB8AincI4GWpBoDOh9g9P/dcgQ7LIMMIf4HXBySgCZR/euQYEllAP1XZyOswMGeW3hSOs6n87uZsim+hhuC+Db3D3Xw/SoZ1pLm5ZKRVi0sVSm9HpxyJDSdYRWPB6rif8VGp1L64Miys7N1k75wdpbhvMBolLOOC9XOx/Oj8EPotHmdO6n3tFTN+3JPH8JUgW7pUq9zg1BS4Z1b5p/gXTZGrCmRHOZknUSAX5u4=,iv:flETH1vzNOoB8fUT8TUyxMNoTs2vWmfa3U0zvDwlpYo=,tag:8DWsMCu442Yi/YsHSDhOWw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNDhMQVA5Tm9paDR4ZDU2
            MlE4bVdIR0JQTWg2MVB3M1lPMEFkZXJzdjM4CnVJKzVzazNOWDdMbVI4YnNmSC94
            TWVBa1ROSGtMTEpSQjI2WEZhV296Qk0KLS0tIGxCQXBoU0NVVFN3Sis0OTJrc0Ur
            RWp5TS9DZnJTS2lnSlo1SGFSWUxrVFkKaLbdspK/Rn7O+FSIKKdE4/xiJQjyN7hm
            HeoWNjh1SvGtBn+dpm84TrPL/B1KVkkwFwi8UT9OeMjxhUliNXH/Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6xujrv4zeja3t8wc3tvwmeel7vfq7f5u3uhy330ym2pvax8p5cqwuuzjt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T20:02:14Z"
    mac: ENC[AES256_GCM,data:eqKLqbPltRBDGz11PJsaBeEpBLGiMYz7gedLs3h15jbHbDjaqtErDiiV2N8Fk1Kuaz6xUxf7JK5cVXCN23Mxrw/xR2jNDFmbaLY5ktRDex5E5lJI0Ur5j8jTfx/8UrTBPfnCxFp5fbJOQGZZG3mBEpUbzLKurs00CrJoay/CkAA=,iv:wr3IXJenhlzKJHab3+LGM+IzZ8OcJiKIx3syR/E7Rbs=,tag:rTlntDFQT6MN4EcyT5GsaA==,type:str]
    version: 3.13.3
