apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:A9zduVITUoA=,iv:CS4mFocZE9aZYtNHUbifTJ516i2VDlCPNWXJQTlDsGc=,tag:tkz++6Ilyds2PzrKAxuCig==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:iu+EoAs5vAoWq59XvSZ4EA==,iv:dYyBeaP0TOpseamJwjpA0DM4C3BCdLtz+qS1jExYPG8=,tag:5dv3+OPQjm2ILceAHW3prA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL3J3akpMYVdsYXpRWGJS
            ZFByZ2YyMi9aNkxZd3g4aDBRZHNtM3Z0ZURzCkdoNnYrd0YvRTNsOUpEdUg1Y21J
            U1VLcjhxZTVsNUNFaVEyTUZVWGFNMFkKLS0tIG9HV2k0Q3ROd0VnUWRoV0kvTzZh
            UnEvZDN6UTBhVm0zbnlCSEl2cmVXOXMKw8beI2L+cK74ghcvh+ZXoAPNBpPF3TVq
            zaBzmkBve0xFHWqyZ1XK9GEowW9JQ+ELgLrdZoP2D9sRF0SqiSzNEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6xujrv4zeja3t8wc3tvwmeel7vfq7f5u3uhy330ym2pvax8p5cqwuuzjt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T20:14:00Z"
    mac: ENC[AES256_GCM,data:0GcJ68pleM6RWThyZhAyDXP31Np9rqVA63a5d8BEeqSoCjKbgXvqAWV1xWfiNa9DpZ3leabvjj5+T99mQwk7Hy5c+dhEJBdGJkrhMi7ezF+E9jGr5O++RlLiaCcW5PEu8A7OI5jmSCVF5CabXmCtrhmaN8VTGB5IbTTLV0eLlWU=,iv:Tk7yA22pgOR7chfVKt68W7GqwkHdUwiIChr6yHKrLcQ=,tag:oavQqX0bPUYCdYBG7K1T4Q==,type:str]
    version: 3.13.3
