apiVersion: v1
data:
    password: ENC[AES256_GCM,data:oP/wcz3uOdTIzmLpEW8bTw==,iv:ZLbJy4P1lhXOOvRAqHbRG8W0AD1mm4njYQGgPBi/pw8=,tag:P53q3FdO+CeLrrLEhVuZ8A==,type:str]
    user: ENC[AES256_GCM,data:rgRvSniChqY=,iv:UQmuhqnBOpUVZqPwfxFXNMpIzGROtulv/HnthBvMnTI=,tag:qUFgW2Sj9KQwPyCTWdX53A==,type:str]
kind: Secret
metadata:
    name: linkding-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaTN5U1ByemdQSEZQR0dN
            NkZiZUtXSmNmcW93SU5UZVVQM1pHQWhaZlc0Clhzd0FYd2RtcHdtVGNhR3FJSlcx
            Sy9LWVBpZkp0TXJQaDdqODVzUFBLK0EKLS0tIEtVZ2lic2c4elNnUkFOVHV5UzFD
            NjJoUzJOTjFhQkFXMlY4RlQrNFZtQjgKNbk1T/2Vpm3v6gkEWbmdC0Ovk00qRWzF
            uxWmTb8clnQiUoUe3zQ1lOW73l2qD28nPa35Udh6uBKY1UGGmP7aBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j6xujrv4zeja3t8wc3tvwmeel7vfq7f5u3uhy330ym2pvax8p5cqwuuzjt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T16:38:10Z"
    mac: ENC[AES256_GCM,data:F1C2DjWU3mVWJbCWxsRrgtCcoXzPJhG+tLtxy9yDekVBV7QfXaIQaebJzFQ6FVKE+12uj8W9pLJ9laqqsK3T7H1hhKCytez1sR4BvYqq/OzDzWufMtJg17XPEs/z12IkaLz8wNNS7C9XcsrXCQmzDTS4TMEUQiXXycKsZdwwVkk=,iv:En/LH1RKY+llz5Rwh6yCvpC9XqoMpb4keBplFPx9SO8=,tag:HAlrdW7Z6GyXfKkjTT4sYg==,type:str]
    version: 3.13.3
